/*
*   
*
* Start two servers...
*   Ask one of them to contact the other...
*   Just start with basic ping/pong
*
*   Maybe test some errors... like when one times out...
*   Or some other kind of error...
*       make sure the other one can notice, and clean up the dead one
*
*/
