#!/bin/bash
# build_and_run.sh
# Usage: ./build_and_run.sh file.cpp

# Exit on error
set -e

# Check for argument
if [ $# -lt 1 ]; then
    echo "Usage: $0 <file.cpp>"
    exit 1
fi

# Extract filename and basename
base="$1"
file="${base}.cpp"
src_path="./tests/$file"
build_path="./tests/build"

# Check if file exists
if [ ! -f "$src_path" ]; then
    echo "Error: File '$src_path' not found."
    exit 1
fi

# Build
echo "Compiling $file..."
g++ -std=c++20 -Wall -Wextra -O2 "$src_path" -o "$build_path/$base" \
    -L./build -lbullet_db \
    -I./deps/blst/bindings \
    -L./deps/blst -lblst
    

# Run
echo "Running $build_path/$base"
echo "=================================="
if [ -n "$2" ]; then
    "$build_path/$base" -"$2"
else
    "$build_path/$base"
fi
